// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: employees.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDepartments = `-- name: CountDepartments :one
SELECT COUNT(*) FROM departments 
WHERE tenant_id = $1 AND is_active = TRUE
`

func (q *Queries) CountDepartments(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartments, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployees = `-- name: CountEmployees :one
SELECT COUNT(*) FROM employees 
WHERE tenant_id = $1 AND is_active = TRUE
`

func (q *Queries) CountEmployees(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPositions = `-- name: CountPositions :one
SELECT COUNT(*) FROM positions 
WHERE tenant_id = $1 AND is_active = TRUE
`

func (q *Queries) CountPositions(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPositions, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchEmployees = `-- name: CountSearchEmployees :one
SELECT COUNT(*) FROM employees e
WHERE 
    e.tenant_id = $1
AND
    (e.first_name ILIKE '%' || $2::text || '%' 
     OR e.last_name ILIKE '%' || $2::text || '%' 
     OR e.email ILIKE '%' || $2::text || '%'
     OR $2::text = '')
AND
    (e.department_id = $3 OR $3 IS NULL)
AND
    (e.position_id = $4 OR $4 IS NULL)
AND
    (e.is_active = $5 OR $5 IS NULL)
AND
    (e.hire_date >= $6 OR $6 IS NULL)
AND
    (e.hire_date <= $7 OR $7 IS NULL)
`

type CountSearchEmployeesParams struct {
	TenantID      uuid.UUID `json:"tenantId"`
	Search        string    `json:"search"`
	DepartmentID  uuid.UUID `json:"departmentId"`
	PositionID    uuid.UUID `json:"positionId"`
	IsActive      bool      `json:"isActive"`
	HireDateStart time.Time `json:"hireDateStart"`
	HireDateEnd   time.Time `json:"hireDateEnd"`
}

func (q *Queries) CountSearchEmployees(ctx context.Context, arg CountSearchEmployeesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchEmployees,
		arg.TenantID,
		arg.Search,
		arg.DepartmentID,
		arg.PositionID,
		arg.IsActive,
		arg.HireDateStart,
		arg.HireDateEnd,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (tenant_id, name, description) 
VALUES ($1, $2, $3) 
RETURNING id, tenant_id, name, description, manager_id, is_active, created_at, updated_at
`

type CreateDepartmentParams struct {
	TenantID    uuid.UUID `json:"tenantId"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.TenantID, arg.Name, arg.Description)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ManagerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
    tenant_id,
    user_id,
    first_name, 
    last_name, 
    email, 
    phone, 
    address, 
    hire_date, 
    termination_date, 
    position_id, 
    department_id, 
    salary, 
    emergency_contact_name, 
    emergency_contact_phone, 
    profile_description, 
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, tenant_id, user_id, first_name, last_name, email, phone, address, hire_date, termination_date, position_id, department_id, salary, emergency_contact_name, emergency_contact_phone, profile_description, is_active, created_at, updated_at
`

type CreateEmployeeParams struct {
	TenantID              uuid.UUID      `json:"tenantId"`
	UserID                *uuid.UUID     `json:"userId"`
	FirstName             string         `json:"firstName"`
	LastName              string         `json:"lastName"`
	Email                 string         `json:"email"`
	Phone                 *string        `json:"phone"`
	Address               *string        `json:"address"`
	HireDate              time.Time      `json:"hireDate"`
	TerminationDate       *time.Time     `json:"terminationDate"`
	PositionID            uuid.UUID      `json:"positionId"`
	DepartmentID          uuid.UUID      `json:"departmentId"`
	Salary                pgtype.Numeric `json:"salary"`
	EmergencyContactName  *string        `json:"emergencyContactName"`
	EmergencyContactPhone *string        `json:"emergencyContactPhone"`
	ProfileDescription    *string        `json:"profileDescription"`
	IsActive              bool           `json:"isActive"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.TenantID,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.HireDate,
		arg.TerminationDate,
		arg.PositionID,
		arg.DepartmentID,
		arg.Salary,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.ProfileDescription,
		arg.IsActive,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.HireDate,
		&i.TerminationDate,
		&i.PositionID,
		&i.DepartmentID,
		&i.Salary,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.ProfileDescription,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (tenant_id, title, description, level, is_management) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING id, tenant_id, title, description, level, is_management, is_active, created_at, updated_at
`

type CreatePositionParams struct {
	TenantID     uuid.UUID   `json:"tenantId"`
	Title        string      `json:"title"`
	Description  *string     `json:"description"`
	Level        pgtype.Int4 `json:"level"`
	IsManagement bool        `json:"isManagement"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition,
		arg.TenantID,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.IsManagement,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.IsManagement,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments 
WHERE id = $1 AND tenant_id = $2
`

type DeleteDepartmentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenantId"`
}

func (q *Queries) DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) error {
	_, err := q.db.Exec(ctx, deleteDepartment, arg.ID, arg.TenantID)
	return err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees 
WHERE id = $1 AND tenant_id = $2
`

type DeleteEmployeeParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenantId"`
}

func (q *Queries) DeleteEmployee(ctx context.Context, arg DeleteEmployeeParams) error {
	_, err := q.db.Exec(ctx, deleteEmployee, arg.ID, arg.TenantID)
	return err
}

const deletePosition = `-- name: DeletePosition :exec
DELETE FROM positions 
WHERE id = $1 AND tenant_id = $2
`

type DeletePositionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenantId"`
}

func (q *Queries) DeletePosition(ctx context.Context, arg DeletePositionParams) error {
	_, err := q.db.Exec(ctx, deletePosition, arg.ID, arg.TenantID)
	return err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, tenant_id, name, description, manager_id, is_active, created_at, updated_at FROM departments 
WHERE id = $1 AND tenant_id = $2
`

type GetDepartmentByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenantId"`
}

func (q *Queries) GetDepartmentByID(ctx context.Context, arg GetDepartmentByIDParams) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, arg.ID, arg.TenantID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ManagerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeById = `-- name: GetEmployeeById :one
SELECT id, tenant_id, user_id, first_name, last_name, email, phone, address, hire_date, termination_date, position_id, department_id, salary, emergency_contact_name, emergency_contact_phone, profile_description, is_active, created_at, updated_at FROM employees 
WHERE id = $1 AND tenant_id = $2 
LIMIT 1
`

type GetEmployeeByIdParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenantId"`
}

func (q *Queries) GetEmployeeById(ctx context.Context, arg GetEmployeeByIdParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeById, arg.ID, arg.TenantID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.HireDate,
		&i.TerminationDate,
		&i.PositionID,
		&i.DepartmentID,
		&i.Salary,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.ProfileDescription,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPosition = `-- name: GetPosition :one
SELECT id, tenant_id, title, description, level, is_management, is_active, created_at, updated_at FROM positions 
WHERE id = $1 AND tenant_id = $2
`

type GetPositionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenantId"`
}

func (q *Queries) GetPosition(ctx context.Context, arg GetPositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPosition, arg.ID, arg.TenantID)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.IsManagement,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many

SELECT id, tenant_id, name, description, manager_id, is_active, created_at, updated_at FROM departments 
WHERE tenant_id = $1 AND is_active = TRUE
ORDER BY name ASC
`

// ============ DEPARTMENT QUERIES ============
func (q *Queries) ListDepartments(ctx context.Context, tenantID uuid.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.ManagerID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many

SELECT id, tenant_id, user_id, first_name, last_name, email, phone, address, hire_date, termination_date, position_id, department_id, salary, emergency_contact_name, emergency_contact_phone, profile_description, is_active, created_at, updated_at FROM employees 
WHERE tenant_id = $1 AND is_active = TRUE
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEmployeesParams struct {
	TenantID uuid.UUID `json:"tenantId"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

// ============ EMPLOYEE QUERIES ============
func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.HireDate,
			&i.TerminationDate,
			&i.PositionID,
			&i.DepartmentID,
			&i.Salary,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.ProfileDescription,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many

SELECT id, tenant_id, title, description, level, is_management, is_active, created_at, updated_at FROM positions 
WHERE tenant_id = $1 AND is_active = TRUE
ORDER BY title ASC
`

// ============ POSITION QUERIES ============
func (q *Queries) ListPositions(ctx context.Context, tenantID uuid.UUID) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.IsManagement,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEmployees = `-- name: SearchEmployees :many
SELECT 
    e.id, e.tenant_id, e.user_id, e.first_name, e.last_name, e.email, e.phone, e.address, e.hire_date, e.termination_date, e.position_id, e.department_id, e.salary, e.emergency_contact_name, e.emergency_contact_phone, e.profile_description, e.is_active, e.created_at, e.updated_at,
    d.name as department_name,
    p.title as position_title
FROM employees e
JOIN departments d ON e.department_id = d.id
JOIN positions p ON e.position_id = p.id
WHERE 
    e.tenant_id = $1
AND
    (e.first_name ILIKE '%' || $2::text || '%' 
     OR e.last_name ILIKE '%' || $2::text || '%' 
     OR e.email ILIKE '%' || $2::text || '%'
     OR $2::text = '')
AND
    (e.department_id = $3 OR $3 IS NULL)
AND
    (e.position_id = $4 OR $4 IS NULL)
AND
    (e.is_active = $5 OR $5 IS NULL)
AND
    (e.hire_date >= $6 OR $6 IS NULL)
AND
    (e.hire_date <= $7 OR $7 IS NULL)
ORDER BY e.created_at DESC
LIMIT $9 OFFSET $8
`

type SearchEmployeesParams struct {
	TenantID      uuid.UUID `json:"tenantId"`
	Search        string    `json:"search"`
	DepartmentID  uuid.UUID `json:"departmentId"`
	PositionID    uuid.UUID `json:"positionId"`
	IsActive      bool      `json:"isActive"`
	HireDateStart time.Time `json:"hireDateStart"`
	HireDateEnd   time.Time `json:"hireDateEnd"`
	OffsetCount   int32     `json:"offsetCount"`
	LimitCount    int32     `json:"limitCount"`
}

type SearchEmployeesRow struct {
	ID                    uuid.UUID      `json:"id"`
	TenantID              uuid.UUID      `json:"tenantId"`
	UserID                *uuid.UUID     `json:"userId"`
	FirstName             string         `json:"firstName"`
	LastName              string         `json:"lastName"`
	Email                 string         `json:"email"`
	Phone                 *string        `json:"phone"`
	Address               *string        `json:"address"`
	HireDate              time.Time      `json:"hireDate"`
	TerminationDate       *time.Time     `json:"terminationDate"`
	PositionID            uuid.UUID      `json:"positionId"`
	DepartmentID          uuid.UUID      `json:"departmentId"`
	Salary                pgtype.Numeric `json:"salary"`
	EmergencyContactName  *string        `json:"emergencyContactName"`
	EmergencyContactPhone *string        `json:"emergencyContactPhone"`
	ProfileDescription    *string        `json:"profileDescription"`
	IsActive              bool           `json:"isActive"`
	CreatedAt             time.Time      `json:"createdAt"`
	UpdatedAt             time.Time      `json:"updatedAt"`
	DepartmentName        string         `json:"departmentName"`
	PositionTitle         string         `json:"positionTitle"`
}

func (q *Queries) SearchEmployees(ctx context.Context, arg SearchEmployeesParams) ([]SearchEmployeesRow, error) {
	rows, err := q.db.Query(ctx, searchEmployees,
		arg.TenantID,
		arg.Search,
		arg.DepartmentID,
		arg.PositionID,
		arg.IsActive,
		arg.HireDateStart,
		arg.HireDateEnd,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEmployeesRow{}
	for rows.Next() {
		var i SearchEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.HireDate,
			&i.TerminationDate,
			&i.PositionID,
			&i.DepartmentID,
			&i.Salary,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.ProfileDescription,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DepartmentName,
			&i.PositionTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDepartment = `-- name: SoftDeleteDepartment :exec
UPDATE departments 
SET 
    is_active = FALSE,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
`

type SoftDeleteDepartmentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenantId"`
}

func (q *Queries) SoftDeleteDepartment(ctx context.Context, arg SoftDeleteDepartmentParams) error {
	_, err := q.db.Exec(ctx, softDeleteDepartment, arg.ID, arg.TenantID)
	return err
}

const softDeleteEmployee = `-- name: SoftDeleteEmployee :one
UPDATE employees 
SET 
    is_active = FALSE,
    termination_date = $2,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $3
RETURNING id, tenant_id, user_id, first_name, last_name, email, phone, address, hire_date, termination_date, position_id, department_id, salary, emergency_contact_name, emergency_contact_phone, profile_description, is_active, created_at, updated_at
`

type SoftDeleteEmployeeParams struct {
	ID              uuid.UUID  `json:"id"`
	TerminationDate *time.Time `json:"terminationDate"`
	TenantID        uuid.UUID  `json:"tenantId"`
}

func (q *Queries) SoftDeleteEmployee(ctx context.Context, arg SoftDeleteEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, softDeleteEmployee, arg.ID, arg.TerminationDate, arg.TenantID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.HireDate,
		&i.TerminationDate,
		&i.PositionID,
		&i.DepartmentID,
		&i.Salary,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.ProfileDescription,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeletePosition = `-- name: SoftDeletePosition :exec
UPDATE positions 
SET 
    is_active = FALSE,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
`

type SoftDeletePositionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenantId"`
}

func (q *Queries) SoftDeletePosition(ctx context.Context, arg SoftDeletePositionParams) error {
	_, err := q.db.Exec(ctx, softDeletePosition, arg.ID, arg.TenantID)
	return err
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments 
SET 
    name = $2, 
    description = $3,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $4
RETURNING id, tenant_id, name, description, manager_id, is_active, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	TenantID    uuid.UUID `json:"tenantId"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TenantID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ManagerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET 
    user_id = $2,
    first_name = $3,
    last_name = $4,
    email = $5,
    phone = $6,
    address = $7,
    hire_date = $8,
    termination_date = $9,
    position_id = $10,
    department_id = $11,
    salary = $12,
    emergency_contact_name = $13,
    emergency_contact_phone = $14,
    profile_description = $15,
    is_active = $16,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $17
RETURNING id, tenant_id, user_id, first_name, last_name, email, phone, address, hire_date, termination_date, position_id, department_id, salary, emergency_contact_name, emergency_contact_phone, profile_description, is_active, created_at, updated_at
`

type UpdateEmployeeParams struct {
	ID                    uuid.UUID      `json:"id"`
	UserID                *uuid.UUID     `json:"userId"`
	FirstName             string         `json:"firstName"`
	LastName              string         `json:"lastName"`
	Email                 string         `json:"email"`
	Phone                 *string        `json:"phone"`
	Address               *string        `json:"address"`
	HireDate              time.Time      `json:"hireDate"`
	TerminationDate       *time.Time     `json:"terminationDate"`
	PositionID            uuid.UUID      `json:"positionId"`
	DepartmentID          uuid.UUID      `json:"departmentId"`
	Salary                pgtype.Numeric `json:"salary"`
	EmergencyContactName  *string        `json:"emergencyContactName"`
	EmergencyContactPhone *string        `json:"emergencyContactPhone"`
	ProfileDescription    *string        `json:"profileDescription"`
	IsActive              bool           `json:"isActive"`
	TenantID              uuid.UUID      `json:"tenantId"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.HireDate,
		arg.TerminationDate,
		arg.PositionID,
		arg.DepartmentID,
		arg.Salary,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.ProfileDescription,
		arg.IsActive,
		arg.TenantID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.HireDate,
		&i.TerminationDate,
		&i.PositionID,
		&i.DepartmentID,
		&i.Salary,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.ProfileDescription,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions 
SET 
    title = $2, 
    description = $3, 
    level = $4, 
    is_management = $5,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $6
RETURNING id, tenant_id, title, description, level, is_management, is_active, created_at, updated_at
`

type UpdatePositionParams struct {
	ID           uuid.UUID   `json:"id"`
	Title        string      `json:"title"`
	Description  *string     `json:"description"`
	Level        pgtype.Int4 `json:"level"`
	IsManagement bool        `json:"isManagement"`
	TenantID     uuid.UUID   `json:"tenantId"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, updatePosition,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.IsManagement,
		arg.TenantID,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.IsManagement,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
