// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: employees.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDepartments = `-- name: CountDepartments :one
SELECT COUNT(*) FROM departments
`

func (q *Queries) CountDepartments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployees = `-- name: CountEmployees :one
SELECT COUNT(*) FROM employees
`

func (q *Queries) CountEmployees(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPositions = `-- name: CountPositions :one
SELECT COUNT(*) FROM positions
`

func (q *Queries) CountPositions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPositions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchEmployees = `-- name: CountSearchEmployees :one
SELECT COUNT(*) FROM employees
WHERE 
  (first_name ILIKE '%' || $1 || '%' OR last_name ILIKE '%' || $1 || '%' OR $1 = '')
AND
  (department_id = $2 OR $2 IS NULL)
AND
  (position_id = $3 OR $3 IS NULL)
AND
  (is_active = $4 OR $4 IS NULL)
AND
  (hire_date BETWEEN $5 AND $6 OR ($5 IS NULL AND $6 IS NULL))
`

type CountSearchEmployeesParams struct {
	Column1      pgtype.Text `json:"column1"`
	DepartmentID pgtype.UUID `json:"departmentId"`
	PositionID   pgtype.UUID `json:"positionId"`
	IsActive     pgtype.Bool `json:"isActive"`
	HireDate     pgtype.Date `json:"hireDate"`
	HireDate_2   pgtype.Date `json:"hireDate2"`
}

func (q *Queries) CountSearchEmployees(ctx context.Context, arg CountSearchEmployeesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchEmployees,
		arg.Column1,
		arg.DepartmentID,
		arg.PositionID,
		arg.IsActive,
		arg.HireDate,
		arg.HireDate_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (name, description) VALUES ($1, $2) RETURNING id, owner_id, name, description
`

type CreateDepartmentParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.Name, arg.Description)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
    first_name, 
    last_name, 
    email, 
    phone, 
    address, 
    hire_date, 
    termination_date, 
    position_id, 
    department_id, 
    salary, 
    emergency_contact_name, 
    emergency_contact_phone, 
    profile_description, 
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, user_id, owner_id, first_name, last_name, email, phone, address, hire_date, termination_date, position_id, department_id, salary, emergency_contact_name, emergency_contact_phone, profile_description, is_active, created_at, updated_at
`

type CreateEmployeeParams struct {
	FirstName             string         `json:"firstName"`
	LastName              string         `json:"lastName"`
	Email                 string         `json:"email"`
	Phone                 pgtype.Text    `json:"phone"`
	Address               pgtype.Text    `json:"address"`
	HireDate              pgtype.Date    `json:"hireDate"`
	TerminationDate       pgtype.Date    `json:"terminationDate"`
	PositionID            pgtype.UUID    `json:"positionId"`
	DepartmentID          pgtype.UUID    `json:"departmentId"`
	Salary                pgtype.Numeric `json:"salary"`
	EmergencyContactName  pgtype.Text    `json:"emergencyContactName"`
	EmergencyContactPhone pgtype.Text    `json:"emergencyContactPhone"`
	ProfileDescription    pgtype.Text    `json:"profileDescription"`
	IsActive              pgtype.Bool    `json:"isActive"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.HireDate,
		arg.TerminationDate,
		arg.PositionID,
		arg.DepartmentID,
		arg.Salary,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.ProfileDescription,
		arg.IsActive,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OwnerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.HireDate,
		&i.TerminationDate,
		&i.PositionID,
		&i.DepartmentID,
		&i.Salary,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.ProfileDescription,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions ( title, description, level, is_management) VALUES ($1, $2, $3, $4) RETURNING id, owner_id, title, description, level, is_management
`

type CreatePositionParams struct {
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	Level        pgtype.Int4 `json:"level"`
	IsManagement pgtype.Bool `json:"isManagement"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.IsManagement,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.IsManagement,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepartment, id)
	return err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}

const deletePosition = `-- name: DeletePosition :exec
DELETE FROM positions WHERE id = $1
`

func (q *Queries) DeletePosition(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePosition, id)
	return err
}

const getEmployeeById = `-- name: GetEmployeeById :one
SELECT id, user_id, owner_id, first_name, last_name, email, phone, address, hire_date, termination_date, position_id, department_id, salary, emergency_contact_name, emergency_contact_phone, profile_description, is_active, created_at, updated_at FROM employees WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmployeeById(ctx context.Context, id pgtype.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeById, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OwnerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.HireDate,
		&i.TerminationDate,
		&i.PositionID,
		&i.DepartmentID,
		&i.Salary,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.ProfileDescription,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, owner_id, name, description FROM departments
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, user_id, owner_id, first_name, last_name, email, phone, address, hire_date, termination_date, position_id, department_id, salary, emergency_contact_name, emergency_contact_phone, profile_description, is_active, created_at, updated_at FROM employees ORDER BY id LIMIT $1 OFFSET $2
`

type ListEmployeesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OwnerID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.HireDate,
			&i.TerminationDate,
			&i.PositionID,
			&i.DepartmentID,
			&i.Salary,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.ProfileDescription,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many
SELECT id, owner_id, title, description, level, is_management FROM positions
`

func (q *Queries) ListPositions(ctx context.Context) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.IsManagement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEmployees = `-- name: SearchEmployees :many
SELECT id, user_id, owner_id, first_name, last_name, email, phone, address, hire_date, termination_date, position_id, department_id, salary, emergency_contact_name, emergency_contact_phone, profile_description, is_active, created_at, updated_at FROM employees
WHERE 
  (first_name ILIKE '%' || $1 || '%' OR last_name ILIKE '%' || $1 || '%' OR $1 = '')
AND
  (department_id = $2 OR $2 IS NULL)
AND
  (position_id = $3 OR $3 IS NULL)
AND
  (is_active = $4 OR $4 IS NULL)
AND
  (hire_date BETWEEN $5 AND $6 OR ($5 IS NULL AND $6 IS NULL))
ORDER BY id
LIMIT $7 OFFSET $8
`

type SearchEmployeesParams struct {
	Column1      pgtype.Text `json:"column1"`
	DepartmentID pgtype.UUID `json:"departmentId"`
	PositionID   pgtype.UUID `json:"positionId"`
	IsActive     pgtype.Bool `json:"isActive"`
	HireDate     pgtype.Date `json:"hireDate"`
	HireDate_2   pgtype.Date `json:"hireDate2"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

func (q *Queries) SearchEmployees(ctx context.Context, arg SearchEmployeesParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, searchEmployees,
		arg.Column1,
		arg.DepartmentID,
		arg.PositionID,
		arg.IsActive,
		arg.HireDate,
		arg.HireDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OwnerID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.HireDate,
			&i.TerminationDate,
			&i.PositionID,
			&i.DepartmentID,
			&i.Salary,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.ProfileDescription,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :exec
UPDATE departments set name = $2, description = $3 WHERE id = $1
`

type UpdateDepartmentParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) error {
	_, err := q.db.Exec(ctx, updateDepartment, arg.ID, arg.Name, arg.Description)
	return err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET 
    first_name = $2,
    last_name = $3,
    email = $4,
    phone = $5,
    address = $6,
    hire_date = $7,
    termination_date = $8,
    position_id = $9,
    department_id = $10,
    salary = $11,
    emergency_contact_name = $12,
    emergency_contact_phone = $13,
    profile_description = $14,
    is_active = $15,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, owner_id, first_name, last_name, email, phone, address, hire_date, termination_date, position_id, department_id, salary, emergency_contact_name, emergency_contact_phone, profile_description, is_active, created_at, updated_at
`

type UpdateEmployeeParams struct {
	ID                    pgtype.UUID    `json:"id"`
	FirstName             string         `json:"firstName"`
	LastName              string         `json:"lastName"`
	Email                 string         `json:"email"`
	Phone                 pgtype.Text    `json:"phone"`
	Address               pgtype.Text    `json:"address"`
	HireDate              pgtype.Date    `json:"hireDate"`
	TerminationDate       pgtype.Date    `json:"terminationDate"`
	PositionID            pgtype.UUID    `json:"positionId"`
	DepartmentID          pgtype.UUID    `json:"departmentId"`
	Salary                pgtype.Numeric `json:"salary"`
	EmergencyContactName  pgtype.Text    `json:"emergencyContactName"`
	EmergencyContactPhone pgtype.Text    `json:"emergencyContactPhone"`
	ProfileDescription    pgtype.Text    `json:"profileDescription"`
	IsActive              pgtype.Bool    `json:"isActive"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.HireDate,
		arg.TerminationDate,
		arg.PositionID,
		arg.DepartmentID,
		arg.Salary,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.ProfileDescription,
		arg.IsActive,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OwnerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.HireDate,
		&i.TerminationDate,
		&i.PositionID,
		&i.DepartmentID,
		&i.Salary,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.ProfileDescription,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePosition = `-- name: UpdatePosition :exec
UPDATE positions set  title = $1, description = $2, level = $3, is_management = $4 WHERE id = $1
`

type UpdatePositionParams struct {
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	Level        pgtype.Int4 `json:"level"`
	IsManagement pgtype.Bool `json:"isManagement"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) error {
	_, err := q.db.Exec(ctx, updatePosition,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.IsManagement,
	)
	return err
}
