// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: menus.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addItemToMenuCategory = `-- name: AddItemToMenuCategory :exec
/* 
name: GetMenuWithItems :many
WITH menu_data AS (
    SELECT * FROM menus WHERE id = $1
),
menu_items_data AS (
    SELECT mi.* 
    FROM menu_items mi
    WHERE mi.id = ANY(
        SELECT jsonb_array_elements_text(categories)::int 
        FROM menu_data
    )
    AND mi.is_active = TRUE
)
SELECT 
    md.*,
    jsonb_agg(mi) AS items
FROM 
    menu_data md
LEFT JOIN 
    menu_items_data mi ON true
GROUP BY 
    md.id;
*/

UPDATE menus
SET categories = jsonb_insert(
    categories, 
    ('{' || array_length(categories::jsonb->$2, 1) || '}')::text[], 
    $1::jsonb
)
WHERE id = $3
`

type AddItemToMenuCategoryParams struct {
	Column1    []byte `json:"column1"`
	Categories []byte `json:"categories"`
	ID         int32  `json:"id"`
}

func (q *Queries) AddItemToMenuCategory(ctx context.Context, arg AddItemToMenuCategoryParams) error {
	_, err := q.db.Exec(ctx, addItemToMenuCategory, arg.Column1, arg.Categories, arg.ID)
	return err
}

const createMenu = `-- name: CreateMenu :one
INSERT INTO menus (name, description, categories, valid_from, valid_to)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, is_active, categories, valid_from, valid_to
`

type CreateMenuParams struct {
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Categories  []byte           `json:"categories"`
	ValidFrom   pgtype.Timestamp `json:"validFrom"`
	ValidTo     pgtype.Timestamp `json:"validTo"`
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, createMenu,
		arg.Name,
		arg.Description,
		arg.Categories,
		arg.ValidFrom,
		arg.ValidTo,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.Categories,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (
    name, description, price, cost, preparation_time, 
    is_vegetarian, is_vegan, is_gluten_free, image_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, description, price, cost, preparation_time, is_vegetarian, is_vegan, is_gluten_free, is_active, image_url, created_at, updated_at
`

type CreateMenuItemParams struct {
	Name            string         `json:"name"`
	Description     pgtype.Text    `json:"description"`
	Price           pgtype.Numeric `json:"price"`
	Cost            pgtype.Numeric `json:"cost"`
	PreparationTime pgtype.Int4    `json:"preparationTime"`
	IsVegetarian    pgtype.Bool    `json:"isVegetarian"`
	IsVegan         pgtype.Bool    `json:"isVegan"`
	IsGlutenFree    pgtype.Bool    `json:"isGlutenFree"`
	ImageUrl        pgtype.Text    `json:"imageUrl"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Cost,
		arg.PreparationTime,
		arg.IsVegetarian,
		arg.IsVegan,
		arg.IsGlutenFree,
		arg.ImageUrl,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Cost,
		&i.PreparationTime,
		&i.IsVegetarian,
		&i.IsVegan,
		&i.IsGlutenFree,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMenu = `-- name: DeleteMenu :exec
DELETE FROM menus WHERE id = $1
`

func (q *Queries) DeleteMenu(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMenu, id)
	return err
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_items WHERE id = $1
`

func (q *Queries) DeleteMenuItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMenuItem, id)
	return err
}

const filterMenuItems = `-- name: FilterMenuItems :many
SELECT id, name, description, price, cost, preparation_time, is_vegetarian, is_vegan, is_gluten_free, is_active, image_url, created_at, updated_at FROM menu_items
WHERE 
    is_active = TRUE
    AND (price <= $1 OR $1 IS NULL)
    AND (is_vegetarian = $2 OR $2 IS NULL)
    AND (is_vegan = $3 OR $3 IS NULL)
    AND (is_gluten_free = $4 OR $4 IS NULL)
    AND (preparation_time <= $5 OR $5 IS NULL)
ORDER BY 
    CASE WHEN $6 = 'price_asc' THEN price END ASC,
    CASE WHEN $6 = 'price_desc' THEN price END DESC,
    CASE WHEN $6 = 'prep_time_asc' THEN preparation_time END ASC,
    CASE WHEN $6 = 'prep_time_desc' THEN preparation_time END DESC,
    name ASC
`

type FilterMenuItemsParams struct {
	Price           pgtype.Numeric `json:"price"`
	IsVegetarian    pgtype.Bool    `json:"isVegetarian"`
	IsVegan         pgtype.Bool    `json:"isVegan"`
	IsGlutenFree    pgtype.Bool    `json:"isGlutenFree"`
	PreparationTime pgtype.Int4    `json:"preparationTime"`
	Column6         interface{}    `json:"column6"`
}

func (q *Queries) FilterMenuItems(ctx context.Context, arg FilterMenuItemsParams) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, filterMenuItems,
		arg.Price,
		arg.IsVegetarian,
		arg.IsVegan,
		arg.IsGlutenFree,
		arg.PreparationTime,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Cost,
			&i.PreparationTime,
			&i.IsVegetarian,
			&i.IsVegan,
			&i.IsGlutenFree,
			&i.IsActive,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveMenuItems = `-- name: GetActiveMenuItems :many
SELECT id, name, description, price, cost, preparation_time, is_vegetarian, is_vegan, is_gluten_free, is_active, image_url, created_at, updated_at FROM menu_items WHERE is_active = TRUE
`

func (q *Queries) GetActiveMenuItems(ctx context.Context) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, getActiveMenuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Cost,
			&i.PreparationTime,
			&i.IsVegetarian,
			&i.IsVegan,
			&i.IsGlutenFree,
			&i.IsActive,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveMenus = `-- name: GetActiveMenus :many
SELECT id, name, description, is_active, categories, valid_from, valid_to FROM menus 
WHERE is_active = TRUE 
AND (valid_from IS NULL OR valid_from <= NOW()) 
AND (valid_to IS NULL OR valid_to >= NOW())
`

func (q *Queries) GetActiveMenus(ctx context.Context) ([]Menu, error) {
	rows, err := q.db.Query(ctx, getActiveMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Menu
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.Categories,
			&i.ValidFrom,
			&i.ValidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMenuByID = `-- name: GetMenuByID :one
SELECT id, name, description, is_active, categories, valid_from, valid_to FROM menus WHERE id = $1
`

func (q *Queries) GetMenuByID(ctx context.Context, id int32) (Menu, error) {
	row := q.db.QueryRow(ctx, getMenuByID, id)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.Categories,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const getMenuItemByID = `-- name: GetMenuItemByID :one
SELECT id, name, description, price, cost, preparation_time, is_vegetarian, is_vegan, is_gluten_free, is_active, image_url, created_at, updated_at FROM menu_items WHERE id = $1
`

func (q *Queries) GetMenuItemByID(ctx context.Context, id int32) (MenuItem, error) {
	row := q.db.QueryRow(ctx, getMenuItemByID, id)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Cost,
		&i.PreparationTime,
		&i.IsVegetarian,
		&i.IsVegan,
		&i.IsGlutenFree,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMenuItemsByCategory = `-- name: GetMenuItemsByCategory :many
/* Extreme cases
 */

SELECT mi.id, mi.name, mi.description, mi.price, mi.cost, mi.preparation_time, mi.is_vegetarian, mi.is_vegan, mi.is_gluten_free, mi.is_active, mi.image_url, mi.created_at, mi.updated_at 
FROM menu_items mi
JOIN menus m ON mi.id = ANY(m.categories::jsonb->>$1::text::int[])
WHERE m.id = $2 AND mi.is_active = TRUE
`

type GetMenuItemsByCategoryParams struct {
	Column1 string `json:"column1"`
	ID      int32  `json:"id"`
}

func (q *Queries) GetMenuItemsByCategory(ctx context.Context, arg GetMenuItemsByCategoryParams) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, getMenuItemsByCategory, arg.Column1, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Cost,
			&i.PreparationTime,
			&i.IsVegetarian,
			&i.IsVegan,
			&i.IsGlutenFree,
			&i.IsActive,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMenuItemsByIDs = `-- name: GetMenuItemsByIDs :many
SELECT id, name, description, price, cost, preparation_time, is_vegetarian, is_vegan, is_gluten_free, is_active, image_url, created_at, updated_at FROM menu_items WHERE id = ANY($1::int[])
`

func (q *Queries) GetMenuItemsByIDs(ctx context.Context, dollar_1 []int32) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, getMenuItemsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Cost,
			&i.PreparationTime,
			&i.IsVegetarian,
			&i.IsVegan,
			&i.IsGlutenFree,
			&i.IsActive,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenu = `-- name: UpdateMenu :one
UPDATE menus
SET 
    name = $2,
    description = $3,
    categories = $4,
    is_active = $5,
    valid_from = $6,
    valid_to = $7
WHERE id = $1
RETURNING id, name, description, is_active, categories, valid_from, valid_to
`

type UpdateMenuParams struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Categories  []byte           `json:"categories"`
	IsActive    pgtype.Bool      `json:"isActive"`
	ValidFrom   pgtype.Timestamp `json:"validFrom"`
	ValidTo     pgtype.Timestamp `json:"validTo"`
}

func (q *Queries) UpdateMenu(ctx context.Context, arg UpdateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, updateMenu,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Categories,
		arg.IsActive,
		arg.ValidFrom,
		arg.ValidTo,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.Categories,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_items
SET 
    name = $2,
    description = $3,
    price = $4,
    cost = $5,
    preparation_time = $6,
    is_vegetarian = $7,
    is_vegan = $8,
    is_gluten_free = $9,
    is_active = $10,
    image_url = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, price, cost, preparation_time, is_vegetarian, is_vegan, is_gluten_free, is_active, image_url, created_at, updated_at
`

type UpdateMenuItemParams struct {
	ID              int32          `json:"id"`
	Name            string         `json:"name"`
	Description     pgtype.Text    `json:"description"`
	Price           pgtype.Numeric `json:"price"`
	Cost            pgtype.Numeric `json:"cost"`
	PreparationTime pgtype.Int4    `json:"preparationTime"`
	IsVegetarian    pgtype.Bool    `json:"isVegetarian"`
	IsVegan         pgtype.Bool    `json:"isVegan"`
	IsGlutenFree    pgtype.Bool    `json:"isGlutenFree"`
	IsActive        pgtype.Bool    `json:"isActive"`
	ImageUrl        pgtype.Text    `json:"imageUrl"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Cost,
		arg.PreparationTime,
		arg.IsVegetarian,
		arg.IsVegan,
		arg.IsGlutenFree,
		arg.IsActive,
		arg.ImageUrl,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Cost,
		&i.PreparationTime,
		&i.IsVegetarian,
		&i.IsVegan,
		&i.IsGlutenFree,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
