// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Department struct {
	ID          pgtype.UUID `json:"id"`
	OwnerID     pgtype.UUID `json:"ownerId"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Employee struct {
	ID                    pgtype.UUID      `json:"id"`
	UserID                pgtype.UUID      `json:"userId"`
	OwnerID               pgtype.UUID      `json:"ownerId"`
	FirstName             string           `json:"firstName"`
	LastName              string           `json:"lastName"`
	Email                 string           `json:"email"`
	Phone                 pgtype.Text      `json:"phone"`
	Address               pgtype.Text      `json:"address"`
	HireDate              pgtype.Date      `json:"hireDate"`
	TerminationDate       pgtype.Date      `json:"terminationDate"`
	PositionID            pgtype.UUID      `json:"positionId"`
	DepartmentID          pgtype.UUID      `json:"departmentId"`
	Salary                pgtype.Numeric   `json:"salary"`
	EmergencyContactName  pgtype.Text      `json:"emergencyContactName"`
	EmergencyContactPhone pgtype.Text      `json:"emergencyContactPhone"`
	ProfileDescription    pgtype.Text      `json:"profileDescription"`
	IsActive              pgtype.Bool      `json:"isActive"`
	CreatedAt             pgtype.Timestamp `json:"createdAt"`
	UpdatedAt             pgtype.Timestamp `json:"updatedAt"`
}

type Menu struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	IsActive    pgtype.Bool      `json:"isActive"`
	Categories  []byte           `json:"categories"`
	ValidFrom   pgtype.Timestamp `json:"validFrom"`
	ValidTo     pgtype.Timestamp `json:"validTo"`
}

type MenuItem struct {
	ID              int32            `json:"id"`
	Name            string           `json:"name"`
	Description     pgtype.Text      `json:"description"`
	Price           pgtype.Numeric   `json:"price"`
	Cost            pgtype.Numeric   `json:"cost"`
	PreparationTime pgtype.Int4      `json:"preparationTime"`
	IsVegetarian    pgtype.Bool      `json:"isVegetarian"`
	IsVegan         pgtype.Bool      `json:"isVegan"`
	IsGlutenFree    pgtype.Bool      `json:"isGlutenFree"`
	IsActive        pgtype.Bool      `json:"isActive"`
	ImageUrl        pgtype.Text      `json:"imageUrl"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
}

type Position struct {
	ID           pgtype.UUID `json:"id"`
	OwnerID      pgtype.UUID `json:"ownerId"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	Level        pgtype.Int4 `json:"level"`
	IsManagement pgtype.Bool `json:"isManagement"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"userId"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type Role struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	PermissionTemplate []byte             `json:"permissionTemplate"`
	IsDefault          pgtype.Bool        `json:"isDefault"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"passwordHash"`
	LastLogin          pgtype.Timestamptz `json:"lastLogin"`
	LoginAttempts      pgtype.Int4        `json:"loginAttempts"`
	IsLocked           pgtype.Bool        `json:"isLocked"`
	LockedUntil        pgtype.Timestamptz `json:"lockedUntil"`
	PasswordResetToken pgtype.Text        `json:"passwordResetToken"`
	TokenExpiry        pgtype.Timestamptz `json:"tokenExpiry"`
	MustChangePassword pgtype.Bool        `json:"mustChangePassword"`
	EmailVerified      pgtype.Bool        `json:"emailVerified"`
	MfaEnabled         pgtype.Bool        `json:"mfaEnabled"`
	LastPasswordChange pgtype.Timestamptz `json:"lastPasswordChange"`
	UserType           string             `json:"userType"`
	DeletedAt          pgtype.Timestamptz `json:"deletedAt"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
}

type UserProfile struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"userId"`
	FullName    pgtype.Text `json:"fullName"`
	Phone       pgtype.Text `json:"phone"`
	AvatarUrl   pgtype.Text `json:"avatarUrl"`
	Timezone    pgtype.Text `json:"timezone"`
	Permissions []byte      `json:"permissions"`
}

type UserToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"userId"`
	Token     string             `json:"token"`
	Type      string             `json:"type"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UsedAt    pgtype.Timestamptz `json:"usedAt"`
}
