// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Department struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ManagerID   pgtype.Int4 `json:"managerId"`
}

type Employee struct {
	ID                    int32            `json:"id"`
	FirstName             string           `json:"firstName"`
	LastName              string           `json:"lastName"`
	Email                 string           `json:"email"`
	Phone                 pgtype.Text      `json:"phone"`
	Address               pgtype.Text      `json:"address"`
	HireDate              pgtype.Date      `json:"hireDate"`
	TerminationDate       pgtype.Date      `json:"terminationDate"`
	PositionID            int32            `json:"positionId"`
	DepartmentID          int32            `json:"departmentId"`
	Salary                pgtype.Numeric   `json:"salary"`
	EmergencyContactName  pgtype.Text      `json:"emergencyContactName"`
	EmergencyContactPhone pgtype.Text      `json:"emergencyContactPhone"`
	ProfileDescription    pgtype.Text      `json:"profileDescription"`
	IsActive              pgtype.Bool      `json:"isActive"`
	CreatedAt             pgtype.Timestamp `json:"createdAt"`
	UpdatedAt             pgtype.Timestamp `json:"updatedAt"`
}

type Menu struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	IsActive    pgtype.Bool      `json:"isActive"`
	Categories  []byte           `json:"categories"`
	ValidFrom   pgtype.Timestamp `json:"validFrom"`
	ValidTo     pgtype.Timestamp `json:"validTo"`
}

type MenuItem struct {
	ID              int32            `json:"id"`
	Name            string           `json:"name"`
	Description     pgtype.Text      `json:"description"`
	Price           pgtype.Numeric   `json:"price"`
	Cost            pgtype.Numeric   `json:"cost"`
	PreparationTime pgtype.Int4      `json:"preparationTime"`
	IsVegetarian    pgtype.Bool      `json:"isVegetarian"`
	IsVegan         pgtype.Bool      `json:"isVegan"`
	IsGlutenFree    pgtype.Bool      `json:"isGlutenFree"`
	IsActive        pgtype.Bool      `json:"isActive"`
	ImageUrl        pgtype.Text      `json:"imageUrl"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
}

type Position struct {
	ID           int32       `json:"id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	Level        pgtype.Int4 `json:"level"`
	IsManagement pgtype.Bool `json:"isManagement"`
}

type RefreshToken struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"userId"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	EmployeeID         int32              `json:"employeeId"`
	Username           string             `json:"username"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"passwordHash"`
	LastLogin          pgtype.Timestamptz `json:"lastLogin"`
	LoginAttempts      pgtype.Int4        `json:"loginAttempts"`
	IsLocked           pgtype.Bool        `json:"isLocked"`
	LockedUntil        pgtype.Timestamptz `json:"lockedUntil"`
	PasswordResetToken pgtype.Text        `json:"passwordResetToken"`
	TokenExpiry        pgtype.Timestamptz `json:"tokenExpiry"`
	MustChangePassword pgtype.Bool        `json:"mustChangePassword"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
}
