// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddItemToMenuCategory(ctx context.Context, arg AddItemToMenuCategoryParams) error
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CheckEmailExistsInTenant(ctx context.Context, arg CheckEmailExistsInTenantParams) (bool, error)
	CheckEmployeeHasUser(ctx context.Context, arg CheckEmployeeHasUserParams) (bool, error)
	CheckTenantSlugExists(ctx context.Context, slug string) (bool, error)
	CheckUsernameExists(ctx context.Context, username string) (bool, error)
	CheckUsernameExistsInTenant(ctx context.Context, arg CheckUsernameExistsInTenantParams) (bool, error)
	ClearPasswordResetToken(ctx context.Context, id uuid.UUID) (User, error)
	CountActiveUsersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountDepartments(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountEmployees(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountPositions(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountProfilesByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountRolesByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountSearchEmployees(ctx context.Context, arg CountSearchEmployeesParams) (int64, error)
	CountTenants(ctx context.Context) (int64, error)
	CountUsersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountUsersByType(ctx context.Context, userType string) (int64, error)
	CountUsersWithFilters(ctx context.Context, arg CountUsersWithFiltersParams) (int64, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error)
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error)
	// ============ REFRESH TOKEN QUERIES ============
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// ============ ROLE QUERIES ============
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	// ============ TENANT QUERIES ============
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// ============ USER QUERIES ============
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// ============ USER PROFILE QUERIES ============
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	// ============ USER TOKEN QUERIES ============
	CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (UserToken, error)
	DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) error
	DeleteEmployee(ctx context.Context, arg DeleteEmployeeParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteMenu(ctx context.Context, id int32) error
	DeleteMenuItem(ctx context.Context, id int32) error
	DeletePosition(ctx context.Context, arg DeletePositionParams) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	DeleteTenantRefreshTokens(ctx context.Context, tenantID uuid.UUID) error
	DeleteUserProfile(ctx context.Context, userID uuid.UUID) error
	DeleteUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	DeleteUserTokens(ctx context.Context, userID uuid.UUID) error
	DeleteUserTokensByType(ctx context.Context, arg DeleteUserTokensByTypeParams) error
	FilterMenuItems(ctx context.Context, arg FilterMenuItemsParams) ([]MenuItem, error)
	GetActiveMenuItems(ctx context.Context) ([]MenuItem, error)
	GetActiveMenus(ctx context.Context) ([]Menu, error)
	GetDepartmentByID(ctx context.Context, arg GetDepartmentByIDParams) (Department, error)
	GetEmployeeById(ctx context.Context, arg GetEmployeeByIdParams) (Employee, error)
	GetEmployeeByUserID(ctx context.Context, arg GetEmployeeByUserIDParams) (Employee, error)
	GetMenuByID(ctx context.Context, id int32) (Menu, error)
	GetMenuItemByID(ctx context.Context, id int32) (MenuItem, error)
	GetMenuItemsByCategory(ctx context.Context, arg GetMenuItemsByCategoryParams) ([]MenuItem, error)
	GetMenuItemsByIDs(ctx context.Context, dollar_1 []int32) ([]MenuItem, error)
	GetPosition(ctx context.Context, arg GetPositionParams) (Position, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetRoleByTenantAndName(ctx context.Context, arg GetRoleByTenantAndNameParams) (Role, error)
	GetStaffUsersByTenant(ctx context.Context, tenantID uuid.UUID) ([]User, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetTenantStats(ctx context.Context, id uuid.UUID) (GetTenantStatsRow, error)
	GetTenantWithStats(ctx context.Context, id uuid.UUID) (GetTenantWithStatsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByResetToken(ctx context.Context, passwordResetToken *string) (User, error)
	GetUserByTenantAndID(ctx context.Context, arg GetUserByTenantAndIDParams) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserProfile(ctx context.Context, userID uuid.UUID) (UserProfile, error)
	GetUserProfileByTenant(ctx context.Context, arg GetUserProfileByTenantParams) (UserProfile, error)
	GetUserToken(ctx context.Context, token string) (UserToken, error)
	GetUserTokenByType(ctx context.Context, arg GetUserTokenByTypeParams) (UserToken, error)
	// ============ JOIN QUERIES ============
	GetUserWithProfile(ctx context.Context, id uuid.UUID) (GetUserWithProfileRow, error)
	GetUserWithTenant(ctx context.Context, id uuid.UUID) (GetUserWithTenantRow, error)
	GetUsersByTenantID(ctx context.Context, tenantID uuid.UUID) ([]User, error)
	LinkUserToEmployee(ctx context.Context, arg LinkUserToEmployeeParams) (Employee, error)
	ListAllTenants(ctx context.Context) ([]Tenant, error)
	ListDefaultRolesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Role, error)
	// ============ DEPARTMENT QUERIES ============
	ListDepartments(ctx context.Context, tenantID uuid.UUID) ([]Department, error)
	// ============ EMPLOYEE QUERIES ============
	ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error)
	// ============ EMPLOYEE-USER LINK QUERIES ============
	ListEmployeesEligibleForUserCreation(ctx context.Context, tenantID uuid.UUID) ([]Employee, error)
	ListEmployeesWithUserStatus(ctx context.Context, tenantID uuid.UUID) ([]ListEmployeesWithUserStatusRow, error)
	// ============ POSITION QUERIES ============
	ListPositions(ctx context.Context, tenantID uuid.UUID) ([]Position, error)
	ListRolesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Role, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	ListTenantsByPlan(ctx context.Context, plan string) ([]Tenant, error)
	ListUserProfilesByTenant(ctx context.Context, tenantID uuid.UUID) ([]UserProfile, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersByTenant(ctx context.Context, tenantID uuid.UUID) ([]User, error)
	ListUsersByTenantAndType(ctx context.Context, arg ListUsersByTenantAndTypeParams) ([]User, error)
	ListUsersByType(ctx context.Context, userType string) ([]User, error)
	// ============ USER MANAGEMENT QUERIES ============
	ListUsersWithFilters(ctx context.Context, arg ListUsersWithFiltersParams) ([]ListUsersWithFiltersRow, error)
	ListUsersWithProfilesByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListUsersWithProfilesByTenantRow, error)
	MarkTokenUsed(ctx context.Context, id uuid.UUID) error
	SearchEmployees(ctx context.Context, arg SearchEmployeesParams) ([]SearchEmployeesRow, error)
	SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) (User, error)
	SoftDeleteDepartment(ctx context.Context, arg SoftDeleteDepartmentParams) error
	SoftDeleteEmployee(ctx context.Context, arg SoftDeleteEmployeeParams) (Employee, error)
	SoftDeletePosition(ctx context.Context, arg SoftDeletePositionParams) error
	SoftDeleteTenant(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error
	UnlinkUserFromEmployee(ctx context.Context, arg UnlinkUserFromEmployeeParams) error
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
	UpdateLoginAttempts(ctx context.Context, arg UpdateLoginAttemptsParams) (User, error)
	UpdateMenu(ctx context.Context, arg UpdateMenuParams) (Menu, error)
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error)
	UpdateUserProfileByTenant(ctx context.Context, arg UpdateUserProfileByTenantParams) (UserProfile, error)
	VerifyEmail(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
