// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(
    SELECT 1 FROM users 
    WHERE email = $1 AND deleted_at IS NULL
)
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(
    SELECT 1 FROM users 
    WHERE username = $1 AND deleted_at IS NULL
)
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const clearPasswordResetToken = `-- name: ClearPasswordResetToken :one
UPDATE users 
SET 
    password_reset_token = NULL,
    token_expiry = NULL,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at
`

func (q *Queries) ClearPasswordResetToken(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, clearPasswordResetToken, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.LastPasswordChange,
		&i.UserType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, user_type) VALUES ($1, $2, $3, $4)
RETURNING id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordHash"`
	UserType     string `json:"userType"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.UserType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.LastPasswordChange,
		&i.UserType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at FROM users 
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.LastPasswordChange,
		&i.UserType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at FROM users 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.LastPasswordChange,
		&i.UserType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at FROM users 
WHERE password_reset_token = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByResetToken(ctx context.Context, passwordResetToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByResetToken, passwordResetToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.LastPasswordChange,
		&i.UserType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at FROM users 
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.LastPasswordChange,
		&i.UserType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at FROM users 
WHERE deleted_at IS NULL 
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.LastLogin,
			&i.LoginAttempts,
			&i.IsLocked,
			&i.LockedUntil,
			&i.PasswordResetToken,
			&i.TokenExpiry,
			&i.MustChangePassword,
			&i.EmailVerified,
			&i.MfaEnabled,
			&i.LastPasswordChange,
			&i.UserType,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByType = `-- name: ListUsersByType :many
SELECT id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at FROM users 
WHERE user_type = $1 AND deleted_at IS NULL 
ORDER BY created_at DESC
`

func (q *Queries) ListUsersByType(ctx context.Context, userType string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByType, userType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.LastLogin,
			&i.LoginAttempts,
			&i.IsLocked,
			&i.LockedUntil,
			&i.PasswordResetToken,
			&i.TokenExpiry,
			&i.MustChangePassword,
			&i.EmailVerified,
			&i.MfaEnabled,
			&i.LastPasswordChange,
			&i.UserType,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :one
UPDATE users 
SET 
    password_reset_token = $2,
    token_expiry = $3,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at
`

type SetPasswordResetTokenParams struct {
	ID                 pgtype.UUID        `json:"id"`
	PasswordResetToken pgtype.Text        `json:"passwordResetToken"`
	TokenExpiry        pgtype.Timestamptz `json:"tokenExpiry"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, setPasswordResetToken, arg.ID, arg.PasswordResetToken, arg.TokenExpiry)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.LastPasswordChange,
		&i.UserType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users 
SET 
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateLoginAttempts = `-- name: UpdateLoginAttempts :one
UPDATE users 
SET 
    login_attempts = $2,
    is_locked = $3,
    locked_until = $4,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at
`

type UpdateLoginAttemptsParams struct {
	ID            pgtype.UUID        `json:"id"`
	LoginAttempts pgtype.Int4        `json:"loginAttempts"`
	IsLocked      pgtype.Bool        `json:"isLocked"`
	LockedUntil   pgtype.Timestamptz `json:"lockedUntil"`
}

func (q *Queries) UpdateLoginAttempts(ctx context.Context, arg UpdateLoginAttemptsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateLoginAttempts,
		arg.ID,
		arg.LoginAttempts,
		arg.IsLocked,
		arg.LockedUntil,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.LastPasswordChange,
		&i.UserType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users 
SET 
    password_hash = $2,
    last_password_change = NOW(),
    must_change_password = $3,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at
`

type UpdatePasswordParams struct {
	ID                 pgtype.UUID `json:"id"`
	PasswordHash       string      `json:"passwordHash"`
	MustChangePassword pgtype.Bool `json:"mustChangePassword"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.ID, arg.PasswordHash, arg.MustChangePassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.LastPasswordChange,
		&i.UserType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET 
    username = $2,
    email = $3,
    last_login = $4,
    login_attempts = $5,
    is_locked = $6,
    locked_until = $7,
    password_reset_token = $8,
    token_expiry = $9,
    must_change_password = $10,
    email_verified = $11,
    mfa_enabled = $12,
    last_password_change = $13,
    user_type = $14,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at
`

type UpdateUserParams struct {
	ID                 pgtype.UUID        `json:"id"`
	Username           string             `json:"username"`
	Email              string             `json:"email"`
	LastLogin          pgtype.Timestamptz `json:"lastLogin"`
	LoginAttempts      pgtype.Int4        `json:"loginAttempts"`
	IsLocked           pgtype.Bool        `json:"isLocked"`
	LockedUntil        pgtype.Timestamptz `json:"lockedUntil"`
	PasswordResetToken pgtype.Text        `json:"passwordResetToken"`
	TokenExpiry        pgtype.Timestamptz `json:"tokenExpiry"`
	MustChangePassword pgtype.Bool        `json:"mustChangePassword"`
	EmailVerified      pgtype.Bool        `json:"emailVerified"`
	MfaEnabled         pgtype.Bool        `json:"mfaEnabled"`
	LastPasswordChange pgtype.Timestamptz `json:"lastPasswordChange"`
	UserType           string             `json:"userType"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.LastLogin,
		arg.LoginAttempts,
		arg.IsLocked,
		arg.LockedUntil,
		arg.PasswordResetToken,
		arg.TokenExpiry,
		arg.MustChangePassword,
		arg.EmailVerified,
		arg.MfaEnabled,
		arg.LastPasswordChange,
		arg.UserType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.LastPasswordChange,
		&i.UserType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyEmail = `-- name: VerifyEmail :one
UPDATE users 
SET 
    email_verified = TRUE,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, email_verified, mfa_enabled, last_password_change, user_type, deleted_at, created_at, updated_at
`

func (q *Queries) VerifyEmail(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, verifyEmail, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.EmailVerified,
		&i.MfaEnabled,
		&i.LastPasswordChange,
		&i.UserType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
