// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    employee_id, username, email, password_hash
) VALUES (
    $1, $2, $3, $4
) RETURNING id, employee_id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, created_at, updated_at
`

type CreateUserParams struct {
	EmployeeID   int32  `json:"employeeId"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordHash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.EmployeeID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, employee_id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, employee_id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, employee_id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementLoginAttempts = `-- name: IncrementLoginAttempts :exec
UPDATE users 
SET login_attempts = login_attempts + 1,
    is_locked = CASE WHEN login_attempts + 1 >= 5 THEN true ELSE false END,
    locked_until = CASE WHEN login_attempts + 1 >= 5 THEN NOW() + INTERVAL '30 minutes' ELSE NULL END
WHERE id = $1
`

func (q *Queries) IncrementLoginAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementLoginAttempts, id)
	return err
}

const resetLoginAttempts = `-- name: ResetLoginAttempts :exec
UPDATE users 
SET login_attempts = 0,
    is_locked = false,
    locked_until = NULL,
    last_login = NOW()
WHERE id = $1
`

func (q *Queries) ResetLoginAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetLoginAttempts, id)
	return err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE users 
SET password_reset_token = $1,
    token_expiry = $2
WHERE email = $3
`

type SetPasswordResetTokenParams struct {
	PasswordResetToken pgtype.Text        `json:"passwordResetToken"`
	TokenExpiry        pgtype.Timestamptz `json:"tokenExpiry"`
	Email              string             `json:"email"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetToken, arg.PasswordResetToken, arg.TokenExpiry, arg.Email)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users 
SET password_hash = $1,
    password_reset_token = NULL,
    token_expiry = NULL,
    must_change_password = $2,
    updated_at = NOW()
WHERE id = $3
`

type UpdatePasswordParams struct {
	PasswordHash       string      `json:"passwordHash"`
	MustChangePassword pgtype.Bool `json:"mustChangePassword"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.MustChangePassword, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    username = $2,
    email = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, employee_id, username, email, password_hash, last_login, login_attempts, is_locked, locked_until, password_reset_token, token_expiry, must_change_password, created_at, updated_at
`

type UpdateUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
		&i.LoginAttempts,
		&i.IsLocked,
		&i.LockedUntil,
		&i.PasswordResetToken,
		&i.TokenExpiry,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
